### ISSUE TITLE
Proto files comments are shown in the documentation

### ISSUE THREAD

**Issue by iljarotar** [metal-stack-cloud/api#126]
The comments in the proto files are displayed in the api documentation as descriptions of messages, services, etc. Currently there are only a few comments, that are randomly shown somewhere in the docs [here](https://github.com/metal-stack-cloud/api/blob/main/docs/docs.json#L1115) and [here](https://metalstack.cloud/en/documentation/api#ClusterServiceCreateResponse).

**Comment by majst01** [comment]
I was thinking to enhance this during the holidays eventually.
