### ISSUE TITLE
Wild idea: No specific requests in API definition, only resources

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack-cloud/api#22]
This would be breaking, but while I was working with the CLI stuff quite a lot, I am wondering if it would be better and more robust to just define a single resource describing the state instead of having individual requests like "createClusterRequest", which are different from the actual entity and update requests. 

Having a resource describing the whole state and just modifying this resource is also how Kubernetes does it and I think it makes it much less error-prone when we want to provide functionality like `apply` for a CLI / more consistent for users who want to do infrastructure as code.

Does anybody have an opinion on this?

**Comment by majst01** [comment]
For cli this would be probably easier, but i guess for the frontend devs this is a nightmare

Maybe both ?

**Comment by Gerrit91** [comment]
It's now too late, we cannot change this anymore I think.
